SELECT
    t.ROW_NO                   ROW_NO
   ,t.CUSTOMER_NAME            CUSTOMER_NAME
   ,t.LATITUDE                 CUSTOMER_LAT
   ,t.LONGITUDE                CUSTOMER_LONG
   ,t.HOUSE_NUMBER             HOUSE_NUMBER
   ,t.CUSTOMER_ADDRESS         CUSTOMER_ADDRESS
   ,t.CUSTOMER_STREET_NAME     CUSTOMER_STREET_NAME
   ,t.NONUNICODE_DISTRICT_NAME NONUNICODE_DISTRICT_NAME
   ,t.PROVINCE                 PROVINCE
FROM    EDW.RAW.TBL_ENSURE_CUSTOMER_LISTING_ADHOC t
ORDER BY t.LATITUDE DESC -- Bắc vào Nam   Việt Nam
        ,t.LONGITUDE     -- Tây sang Đông Việt Nam
        ,t.ROW_NO